- name: Check if k3s is installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Install k3s
  shell: curl -sfL https://get.k3s.io | sh -
  when: not k3s_binary.stat.exists

- name: Ensure k3s is running
  service:
    name: k3s
    state: started
    enabled: yes
  ignore_errors: yes